version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "gznybwf13"
      POSTGRES_DB: "buysell"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.dะบ
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db